services:
  - type: web
    name: malware-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ml_caracteristicas.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: malware_api.settings
      - key: PYTHON_VERSION
        value: 3.11
